---
- name: Download and extract Mac OS X binary
  ansible.builtin.unarchive:
    src: https://github.com/neovim/neovim/releases/latest/download/nvim-macos-{{ ansible_architecture }}.tar.gz
    dest: /usr/local
    remote_src: yes
    extra_opts: --strip-components=1
